apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://raw.githubusercontent.com/fabiand/instanceTypes/main/instanceTypes.yaml

namePrefix: dev-

patches:
# We resize the *\.medium instance types
# Because we want medium to be generally smaller
- path: assets/resize-medium.yaml
  target:
    name: ".*\\.medium"

# The dev env has their own set of GPUs, thus ensure that
# we point to the dev ones.
- path: assets/gpus.json
  target:
    name: "gn.*"

# We don't have enough cap for 8x in dev
# thus delete these VMIT
# Also delete co1 as this is not yet supported
- path: assets/delete.yaml
  target:
    name: ".*\\.8xlarge|co1\\..*"
