apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: staging-

components:
  # We don't have enough cap for 8x in staging
  # thus delete these VMIT
  - ../../components/no_8xlarge

  # Also delete co1 as this is not yet supported
  - ../../components/no_co1

  # We resize the *\.medium instance types
  # Because we want medium to be generally smaller
  - ../../components/resize_medium

patches:
  # The staging env has their own set of GPUs, thus ensure that
  # we point to the staging ones.
  - path: gpus.json
    target:
      name: "gn.*"
