apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: stage-

patches:
  # We resize the *\.medium instance types
  # Because we want medium to be generally smaller
  - path: resize-medium.yaml
    target:
      name: ".*\\.medium"

  # The dev env has their own set of GPUs, thus ensure that
  # we point to the dev ones.
  - path: gpus.json
    target:
      name: "gn.*"

  # We don't have enough cap for 8x in dev
  # thus delete these VMIT
  # Also delete co1 as this is not yet supported
  - path: delete-instancetype.yaml
    target:
      name: ".*\\.8xlarge|co1\\..*"
