apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  # Delete co1 as this is not yet supported
  - ../../components/no_co1

patches:
  # The dev env has their own set of GPUs, thus ensure that
  # we point to the dev ones.
  - path: gpus.json
    target:
      name: "gn.*"
