apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namePrefix: dev-

patches:
- path: resize-medium.yaml
  target:
    name: ".*\\.medium"
- path: our-gpus.yaml
  target:
    name: "gn.*"
- path: delete.yaml
  target:
    name: ".*\\.8xlarge"
